# GitHub Pages Configuration

# Use the gh-pages branch for GitHub Pages
name: GitHub Pages
on:
  # Manually triggered workflow
  workflow_dispatch:
  # Triggered when code is pushed to the main branch
  push:
    branches: [ main ]
  # Triggered when a pull request is opened or updated
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
