name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build with Docker
        env:
          DOCKER_USER: "1001:1001"
        run: ./dev.sh build

      - name: Upload built assets
        uses: actions/upload-artifact@v4
        with:
          name: built-portfolio
          path: dist/

      # Prepare content for GitHub Pages
      - name: Prepare GitHub Pages content
        # if: github.ref == 'refs/heads/main'
        run: |
          touch dist/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        # if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ github.token }}
